### PR TITLE
@Url to resolve URL against the base URL with set to HttpActionService

### PR DESCRIPTION
**Pull request by dirong**
Also it can be as a url path (@HttpAction.value()) if field value doesn't contain a scheme (http, https, ...).

### CODE REVIEW

**Comment by dkaera** [comment]
That's good idea!

**Comment by sergeyzenchenko** [comment]
hey @dkaera what do you think about our framework?

**Comment by VladSumtsov** [comment]
@sergeyzenchenko Good idea, good framework. Love her! She helps us to make our nights shorter :)

**Comment by sergeyzenchenko** [comment]
@VladSumtsov are you using it in real project right now?

**Comment by VladSumtsov** [comment]
@sergeyzenchenko Still not yet. But, plan to do this in my next project.

**Pull request merged**
